// Senarai dropdown untuk sektor, bahagian, dan JPN

export const sektorOptions = [
  { value: 'SDP', label: 'SDP' },
  { value: 'SDTM', label: 'SDTM' },
  { value: 'SSJK', label: 'SSJK' },
  { value: 'SPK', label: 'SPK' },
  { value: 'SPHEMK', label: 'SPHEMK' },
  { value: 'SPIP', label: 'SPIP' },
];

export const bahagianOptions = [
  { id: 'BKA', name: 'Bahagian Akaun' },
  { id: 'BAS', name: 'Bahagian Audit Sekolah' },
  { id: 'BTP', name: 'Bahagian Tajaan Pendidikan' },
  { id: 'BK', name: 'Bahagian Kewangan' },
  { id: 'BPERMATA', name: 'Bahagian PERMATA' },
  { id: 'BPSHA', name: 'Bahagian Perancangan Strategik dan Hubungan Antarabangsa' },
  { id: 'BKP', name: 'Bahagian Khidmat Pengurusan' },
  { id: 'BMAT', name: 'Bahagian Matrikulasi' },
  { id: 'BPB', name: 'Bahagian Pembangunan' },
  { id: 'BPKUR', name: 'Bahagian Pembangunan Kurikulum' },
  { id: 'BPG', name: 'Bahagian Profesionalisme Guru' },
  { id: 'BPI', name: 'Bahagian Pendidikan Islam' },
  { id: 'BPKHAS', name: 'Bahagian Pendidikan Khas' },
  { id: 'BPS', name: 'Bahagian Pendidikan Swasta' },
  { id: 'BPLTV', name: 'Bahagian Pendidikan dan Latihan Teknikal Vokasional' },
  { id: 'BPM', name: 'Bahagian Pengurusan Maklumat' },
  { id: 'BPSH', name: 'Bahagian Pengurusan Sekolah Harian' },
  { id: 'BPSBP', name: 'Bahagian Pengurusan Sekolah Berasrama Penuh' },
  { id: 'BPSM', name: 'Bahagian Pengurusan Sumber Manusia' },
  { id: 'EPRD', name: 'Bahagian Perancangan dan Penyelidikan Dasar Pendidikan' },
  { id: 'BPR', name: 'Bahagian Perolehan' },
  { id: 'BPKAUN', name: 'Bahagian Psikologi dan Kaunseling' },
  { id: 'BSKK', name: 'Bahagian Sukan, Kokurikulum dan Kesenian' },
  { id: 'BSTP', name: 'Bahagian Sumber dan Teknologi Pendidikan' },
  { id: 'IAB', name: 'Institut Aminuddin Baki' },
  { id: 'IPGM', name: 'Institut Pendidikan Guru Malaysia' },
  { id: 'JN', name: 'Jemaah Nazir' },
  { id: 'LP', name: 'Lembaga Peperiksaan' },
  { id: 'UAD', name: 'Unit Audit Dalam' },
  { id: 'UI', name: 'Unit Integriti' },
  { id: 'UKK', name: 'Unit Komunikasi Korporat' },
  { id: 'PPUU', name: 'Pejabat Penasihat Undang-Undang' },
  { id: 'ELTC', name: 'English Language Training Centre' },
];

export const jpnOptions = [
  { id: 'JPNKL', name: 'JPN Kuala Lumpur', state: 'WP Kuala Lumpur' },
  { id: 'JPNJ', name: 'JPN Johor', state: 'Johor' },
  { id: 'JPNP', name: 'JPN Perak', state: 'Perak' },
  { id: 'JPNK', name: 'JPN Kedah', state: 'Kedah' },
  { id: 'JPNPP', name: 'JPN Pulau Pinang', state: 'Pulau Pinang' },
  { id: 'JPNTRG', name: 'JPN Terengganu', state: 'Terengganu' },
  { id: 'JPNM', name: 'JPN Melaka', state: 'Melaka' },
  { id: 'JPNNS', name: 'JPN Negeri Sembilan', state: 'Negeri Sembilan' },
  { id: 'JPNPHG', name: 'JPN Pahang', state: 'Pahang' },
  { id: 'JPNS', name: 'JPN Selangor', state: 'Selangor' },
  { id: 'JPNPRK', name: 'JPN Perak', state: 'Perak' },
  { id: 'JPNKTN', name: 'JPN Kelantan', state: 'Kelantan' },
  { id: 'JPNSBH', name: 'JPN Sabah', state: 'Sabah' },
  { id: 'JPNSRWK', name: 'JPN Sarawak', state: 'Sarawak' },
  { id: 'JPNSPT', name: 'JPN Putrajaya', state: 'Putrajaya' },
  { id: 'JPNLBU', name: 'JPN Labuan', state: 'Labuan' },
];
